---
title: "Gov 50 Final Project"
author: "Ryan McCarthy"
description: "Not really sure yet"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

My original idea was not possible, so I decided to switch my final project to an analysis of election deniers and median income in their congressional district.  I think this has the potential to be a very interesting final project because I actually have no idea what the outcome will be.  Currently, I am deciding whether I should analyze districts that currently have election deniers in office, districts that have election deniers and districts that have election deniers who are likely to win, or all districts that have election deniers on the ballot.  I think it might be more plausible to go with the second option of districts with current election deniers and deniers who are likely to win their election if they are not incumbents.  Many districts will likely have deniers on the ballot but some may have non-existent chances against high-profile incumbents who will lose by many percentage points, negating the purpose of my analysis.  